### ISSUE TITLE
Which model to run after training .

### ISSUE THREAD

**Issue by thiriveedhisai** [decisionforce/EGPO#5]
Training of model has been finished couldn't figure out how to trained model and simulate , can some one help me out
![WhatsApp Image 2024-03-19 at 5 42 49 PM](https://github.com/decisionforce/EGPO/assets/89006860/ce77c1b2-3196-4d81-9ecc-bfeaf1adf5d8)

**Comment by Shivasairudrangi** [comment]
I need same thing.

**Comment by zxc-phy** [comment]
May I ask if you have solved this problem? I am facing the same demand

**Comment by thiriveedhisai** [comment]
NO 

> May I ask if you have solved this problem? I am facing the same demand

**Comment by pengzhenghao** [comment]
Hi Thanks for reaching out! I have updated a script so that you can evaluate the trained agent in the environment without expert:

https://github.com/decisionforce/EGPO/blob/main/training_script/evaluate_egpo.py

**Comment by zxc-phy** [comment]
Thanks!!!
